version: 0.2
 
phases:
  install:
    commands:
      # install dependencies needed for running tests
      - npm install
 
  build:
    commands:
      # trigger linter
      - npm run lint
      # trigger unit tests
      #- npm run test
      # trigger production build
      - npm run build:prod

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/frontend